name: ingredient_detector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  fluttertoast: ^8.2.12
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
